companies:
  - name: DigitalOcean
    url: http://www.digitalocean.com
    twitter: DigitalOcean
    img: digitalocean.jpg
    diversitydata: NO
    eeo-1: No
    documentation: 
    date-updated: YYYY
    status: No

  - name: Etsy
    url: http://www.etsy.com
    twitter: etsy
    img: etsy.jpg
    diversitydata: Yes
    eeo-1: No
    documentation: https://blog.etsy.com/news/2014/diversity-at-etsy-more-than-just-numbers
    date-updated: 2014
    status: Yes

  - name: Indiegogo
    url: http://www.indiegogo.com
    twitter: indiegogo
    img: indiegogo.jpg
    diversitydata: Yes
    eeo-1: No
    documentation: https://go.indiegogo.com/blog/2014/08/diversity-matters-always.html
    date-updated: 2014
    status: Yes

  - name: KickStarter
    twitter: kickstarter
    url: http://kickstarter.com/
    img: kickstarter.jpg

  - name: Pandora
    url: http://www.pandora.com
    twitter: pandora_radio
    img: pandora.png
    diversitydata: Yes
    eeo-1: No
    documentation: http://www.pandora.com/careers/#diversity
    date-updated: 2014
    status: Yes

  - name: Pinterest
    url: http://www.pinterest.com
    twitter: pinterest
    img: pinterest.png
    diversitydata: Yes
    eeo-1: No
    documentation: https://blog.pinterest.com/en/our-plan-more-diverse-pinterest
    date-updated: 2015
    status: Yes

  - name: Slack
    url: https://www.slack.com
    twitter: SlackHQ
    img: slack.png
    diversitydata: Yes
    eeo-1: No
    documentation: http://slackhq.com/post/128721741660/inclusion-and-diversity-at-slack
    date-updated: 2015
    status: Yes
